- alias: Keith home
  trigger:
    platform: state
    entity_id: device_tracker.androidea3abc784f46ce1e
    from: 'not_home'
    to: 'home'
    state: 'home'
    for:
      seconds: 5
  action:
    service: notify.twilio_sms
    data:
      message: 'You are home'
      target:
        - !secret keith_sms
# - alias: time test
#   trigger:
#     platform: time
#     minutes: '/2' # match every 2 min
#     seconds: 00
#   action:
#     service: notify.gmail
#     # data_template:
#     data:
#       title: "test"
#       message: "test 2"