homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat_coord
  longitude: !secret home_long_coord
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 62
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  # port: 8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: pi
  password: raspberry

switch:
  platform: rpi_rf
  gpio: 17
  switches:
    living_room_light:
      # sw 1
      code_on: 4150275
      code_off: 4150275
      pulselength: 164
      protocol: 1
    switch_2:
      # sw 2
      code_on: 4150284
      code_off: 4150284
      pulselength: 164
      protocol: 1
    switch_3:
      # sw 3
      code_on: 4150320
      code_off: 4150320
      pulselength: 164
      protocol: 1
    switch_4:
      # sw 4
      code_on: 4150464
      code_off: 4150464
      pulselength: 164
      protocol: 1
    switch_5:
      # sw 5
      code_on: 4151040
      code_off: 4151040
      pulselength: 164
      protocol: 1

emulated_hue:
  type: alexa
  expose_by_default: true
  exposed_domains:
    - light
    - switch

device_tracker:
  - platform: ddwrt
    host: 192.168.4.1
    username: admin
    password: !secret device_tracker_ddwrt_password
    consider_home: 60
    interval_seconds: 12

#sensor:
#  - platform: wunderground
#    api_key: !secret sensor_wunderground_api_key
#    monitored_conditions:
#      - alerts
#      - dewpoint_c
#      - dewpoint_f
#      - dewpoint_string
#      - feelslike_c
#      - feelslike_f
#      - feelslike_string
#      - heat_index_c
#      - heat_index_f
#      - heat_index_string
#      - elevation
#      - location
#      - observation_time
#      - precip_1hr_in
#      - precip_1hr_metric
#      - precip_1hr_string
#      - precip_today_in
#      - precip_today_metric
#      - precip_today_string
#      - pressure_in
#      - pressure_mb
#      - pressure_trend
#      - relative_humidity
#      - station_id
#      - solarradiation
#      - temperature_string
#      - temp_c
#      - temp_f
#      - UV
#      - visibility_km
#      - visibility_mi
#      - weather
#      - wind_degrees
#      - wind_dir
#      - wind_gust_kph
#      - wind_gust_mph
#      - wind_kph
#      - wind_mph
#      - wind_string
#
#panel_custom:
#  - name: react
#    sidebar_title: TodoMVC
#    sidebar_icon: mdi:work
#    url_path: todomvc
#    config:
#      title: hello
#

notify:
  - name: twilio_sms
    platform: twilio_sms
    account_sid: !secret notify_twilio_sms_account_sid
    auth_token: !secret notify_twilio_sms_auth_tocken
    from_number: !secret notify_twilio_sms_from_number

automation:
  - alias: Keith home
    trigger:
      platform: state
      entity_id: device_tracker.androidea3abc784f46ce1e
      #  Optional 
      from: 'not_home'
      to: 'home'
      state: 'home'
      for:
        #hours: 1
        #minutes: 10
        seconds: 5
    action:
      service: notify.twilio_sms
      data:
        message: 'Keith is home'
        target:
          - !secret keith_sms
          - !secret eve_sms

