homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat_coord
  longitude: !secret home_long_coord
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 62
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  server_port: 8124
  ssl_certificate: /home/homeassistant/.homeassistant/certs/fullchain.pem
  ssl_key: /home/homeassistant/.homeassistant/certs/privkey.pem

# Checks for available updates
updater:

recorder:
  purge_days: 3

# Discover some devices automatically
#discovery:
#  ignore:
#    - google_cast
#    - denonavr
#    - philips_hue


# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

#mqtt:
#  broker: 127.0.0.1
#  port: 1883
#  client_id: home-assistant-1
#  username: pi
#  password: raspberry

emulated_hue:
  type: alexa
  expose_by_default: true
  exposed_domains:
    - light
    - switch

device_tracker:
  - platform: ddwrt
    host: 192.168.4.1
    username: admin
    password: !secret device_tracker_ddwrt_password
    consider_home: 60
    interval_seconds: 12

#sensor:
#  - platform: wunderground
#    api_key: !secret sensor_wunderground_api_key
#    monitored_conditions:
#      - alerts
#      - dewpoint_c
#      - dewpoint_f
#      - dewpoint_string
#      - feelslike_c
#      - feelslike_f
#      - feelslike_string
#      - heat_index_c
#      - heat_index_f
#      - heat_index_string
#      - elevation
#      - location
#      - observation_time
#      - precip_1hr_in
#      - precip_1hr_metric
#      - precip_1hr_string
#      - precip_today_in
#      - precip_today_metric
#      - precip_today_string
#      - pressure_in
#      - pressure_mb
#      - pressure_trend
#      - relative_humidity
#      - station_id
#      - solarradiation
#      - temperature_string
#      - temp_c
#      - temp_f
#      - UV
#      - visibility_km
#      - visibility_mi
#      - weather
#      - wind_degrees
#      - wind_dir
#      - wind_gust_kph
#      - wind_gust_mph
#      - wind_kph
#      - wind_mph
#      - wind_string


twilio:
  account_sid: !secret notify_twilio_sms_account_sid
  auth_token: !secret notify_twilio_sms_auth_tocken

notify: !include_dir_list notifiers/
automation: !include_dir_list automation/
switch: !include_dir_list switches/
group: !include_dir_merge_named groups/

zwave: !include zwave.yaml

#media_player:
#  - platform: cast
#  - platform: webostv
#    host: 192.168.4.4
#    mac: C8:08:E9:53:EC:81
#    name: living room tv
#    filename: webostv.conf
#    customize:
#      sources:
#        - livetv
#        - youtube

#android_ip_webcam:
#  - host: 192.168.4.7
#    name: Moto G 2nd Gen

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

logger:

