alias: Coming home after dark
trigger:
  platform: state
  entity_id: device_tracker.androidea3abc784f46ce1e, device_tracker.androidf34dc1ff9bd9fbb5
#  state: 'home'
  from: 'not_home'
  to: 'home'
  for:
    seconds: 5
condition:
  condition: sun
  after: sunset
  after_offset: "-0:10"
action:
  service: switch.turn_on
  entity_id: switch.living_room_light

