alias: Coming home after dark
trigger:
  platform: state
  entity_id: device_tracker.androidea3abc784f46ce1e, device_tracker.androidf34dc1ff9bd9fbb5
  state: 'home'
  from: 'not_home'
  to: 'home'
  for:
    seconds: 5
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunset
      after_offset: "-0:10"
    - condition: state
      entity_id: switch.living_room_light
      state: 'off'
action:
  service: switch.turn_on
  entity_id: switch.living_room_light

# action:
#   service: notify.twilio_sms
#   data:
#     message: 'You are home'
#     target:
#       - !secret keith_sms


# from 1 hr after sunset til 10:30pm
#