alias: HTML5 push notification action button clicked
trigger:
  platform: event
  event_type: html5_notification.clicked
  event_data:
    action: open_door
action:
  - service: lock.unlock
    entity_id: lock.front_door_locked

