alias: time test
trigger:
  platform: sun
  event: sunset
  offset: '-04:40:00'

action:
  service: switch.turn_off
  entity_id: switch.switch_5

# trigger:
#   platform: time
#   minutes: '/1'
#   seconds: 00

# action:
#   service: notify.gmail
#   # data_template:
#   data:
#     title: "test"
#     message: "test 2"